# https://help.github.com/en/categories/automating-your-workflow-with-github-actions
name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  composer-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: 8.0

      - run: composer validate --strict

  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: 8.0

      - run: composer install --no-interaction --no-progress --no-suggest

      - run: vendor/bin/phpstan

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4
          - 8.0
          - 8.1

        dependencies:
          - lowest
          - locked
          - highest

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: ${{ matrix.php-version }}

      - if: matrix.dependencies == 'lowest'
        run: composer update --prefer-lowest --no-interaction --no-progress --no-suggest

      - if: matrix.dependencies == 'locked'
        run: composer install --no-interaction --no-progress --no-suggest

      - if: matrix.dependencies == 'highest'
        run: composer update --no-interaction --no-progress --no-suggest

      - run: vendor/bin/phpunit

  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: mbstring
          php-version: 8.0

      - run: composer install --no-interaction --no-progress --no-suggest

      - run: vendor/bin/phpunit --dump-xdebug-filter=.build/phpunit/xdebug-filter.php

      - run: vendor/bin/phpunit --coverage-clover=.build/logs/clover.xml --prepend=.build/phpunit/xdebug-filter.php

      - uses: codecov/codecov-action@v2

  mutation-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: mbstring
          php-version: 8.0

      - run: composer install --no-interaction --no-progress --no-suggest

      - run: vendor/bin/infection --ignore-msi-with-no-mutations --min-covered-msi=100 --min-msi=100
